spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: v4e-initial-load
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  second-datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres2
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      generate_statistics: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  flyway:
    locations=classpath: db-migration
server:
  port: 8500

